// project_react/src/views/HomePage/HomePage.jsx
import { useEffect, useState } from "react";
import { getBlogsList, getCategories, searchBlogs, deleteBlog } from "../../api/blog";
import { Link, useNavigate } from "react-router-dom";
import "./HomePage.scss"
import { useToast } from "../../components/Toast/ToastContext";
import { useAuth } from "../../context/AuthContext";

const HomePage = () => {
    // user state
    const {
        user,
        isLoggedIn,
        isAdmin,
        logout
    } = useAuth();

    const navigate = useNavigate();

    const [searchText, setSearchText] = useState("");
    const [activeCategory, setActiveCategory] = useState("");
    const [allBlogs, setAllBlogs] = useState([]);
    const [allCategories, setAllCategories] = useState([]);
    const [loading, setLoading] = useState(false);
    const [selectedBlog, setSelectedBlog] = useState(null);
    const [deleting, setDeleting] =  useState(false);
    const SERVER_URL = import.meta.env.VITE_SERVER_URL?.replace("/api", "");
    const toast = useToast();

    // get all blogs
    const getBlogs = async (category = activeCategory) => {

        try {

            setLoading(true);
            const result =await getBlogsList(category);

            setAllBlogs(result.data || []);

        } catch (error) {
            console.error(
                "Get blogs error:",
                error
            );
        } finally {
            setLoading(false);

        }
    };

    // search blogs by title
    const handleSearch = async () => {

        try {

            if (!searchText.trim()) {

                await getBlogs();
                return;
            }

            setLoading(true);

            const result = await searchBlogs(searchText.trim());

            setAllBlogs(
                result.data || []
            );

        } catch (error) {

            console.error(
                "Search blogs error:",
                error
            );

        } finally {
            setLoading(false);
        }
    };

    // click category
    const handleClickCategory = async (name) => {

        setActiveCategory(name);

        await getBlogs(name);
    };

    // init page: get categories & blog list
    const initPage = async () => {

        try {

            const result = await getCategories();
            const categories = result.data || [];

            setAllCategories(categories);

            if (categories.length > 0) {

                const firstCategory =categories[0].name;

                setActiveCategory(firstCategory);

                await getBlogs(firstCategory);
            }

        } catch (error) {

            console.error(
                "Init page error:",
                error
            );
        }
    };


    // click btn: post
    const handleClickPost = () => {
        navigate("/addNewBlog");
    };

    // click btn: view post
    const handleClickViewPost = (id) => {
        navigate(`/blogDetail/${id}`);
    };
    
    // click btn: edit
     const handleClickEdit = (id) => {
        navigate(`/editBlog//${id}`);
    };

    // click delete
    const handleDeleteBtn = (blog) => {
        setSelectedBlog(blog);
    };

    const handleDelete = async () => {

        if (!selectedBlog) {
            return;
        }

        try {

            setDeleting(true);

            await deleteBlog(selectedBlog.id);

            await getBlogs();

            setSelectedBlog(null);

            toast.open({
                type: "success",
                title: "Deleted!",
                message:
                    "The blog has been deleted successfully."
            });

        } catch (error) {

            toast.open({
                type: "error",
                title: "Delete failed",
                message: error.message
            });

        } finally {

            setDeleting(false);
        }
    };

    // login
    const handleGoLogin = () => {
        navigate("/login");
    }

    // logout
    const handleLogout = () => {
        logout();

        toast.open({
            type: "success",
            title: "Logout",
            message: "Logout successfully!"
        });
    }

    // format date
    const formatDate = (date) => {

        if (!date) {
            return "";
        }

        return new Date(date)
            .toLocaleDateString(
                "en-US",
                {
                    year: "numeric",
                    month: "short",
                    day: "numeric"
                }
            );
    };

    // init page
    useEffect(() => {

        initPage();

    }, []);

    return (
        <div className="homepage">
            {/* header */}
            <div className="header flex items-center justify-between mb-3 ">
                <h3 className="title">
                    Iris Notes
                </h3>
                <div className="header-right flex">
                    <Link className="about-link" to="/about">
                        About me
                    </Link>
                    {/* post btn */}
                    {isAdmin && (
                        <button
                            type="button"
                            className="btn-post btn btn-pink"
                            onClick={
                                handleClickPost
                            }
                        >
                            + Post
                        </button>
                    )}
                        {/* login */}
                        {!isLoggedIn && (
                            <button className="btn btn-outline-pink" onClick={handleGoLogin}>Login</button>
                        )}
                        
                        {/* show current user */}
                        {isLoggedIn && (
                            <div className="user-area flex">
                                <div className="username px-4 text-2xl flex items-end">
                                    {user?.username}
                                </div>
                                <button
                                    className="btn btn-outline-pink"
                                    onClick={
                                        handleLogout
                                    }
                                >
                                    Logout
                                </button>
                            </div>
                        )}
                </div>
            </div>
            {/* carousel */}
            <div className="carousel-content">
                <div
                    id="carouselExampleCaptions"
                    className="carousel slide"
                    data-bs-ride="carousel"
                >
                    <div className="carousel-indicators">
                        <button
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="0"
                            className="active"
                            aria-current="true"
                            aria-label="Slide 1"
                        />
                        <button
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="1"
                            aria-label="Slide 2"
                        />
                        <button
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="2"
                            aria-label="Slide 3"
                        />
                        <button
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="3"
                            aria-label="Slide 4"
                        />
                    </div>
                    <div className="carousel-inner">
                        <div className="carousel-item active">
                            <img
                                src="/src/assets/imgs/ceramic.png"
                                className="d-block w-100"
                                alt="ceramic"
                            />
                        </div>
                        <div className="carousel-item">
                            <img
                                src="/src/assets/imgs/nail.png"
                                className="d-block w-100"
                                alt="nail"
                            />
                        </div>
                        <div className="carousel-item">
                            <img
                                src="/src/assets/imgs/tea.png"
                                className="d-block w-100"
                                alt="tea"
                            />
                        </div>
                        <div className="carousel-item">
                            <img
                                src="/src/assets/imgs/guzheng.png"
                                className="d-block w-100"
                                alt="guzheng"
                            />
                        </div>
                    </div>

                    <button
                        className="carousel-control-prev"
                        type="button"
                        data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="prev"
                    >
                        <span
                            className="carousel-control-prev-icon"
                            aria-hidden="true"
                        />
                        <span className="visually-hidden">
                            Previous
                        </span>
                    </button>

                    <button
                        className="carousel-control-next"
                        type="button"
                        data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="next"
                    >
                        <span
                            className="carousel-control-next-icon"
                            aria-hidden="true"
                        />
                        <span className="visually-hidden">
                            Next
                        </span>
                    </button>
                </div>
            </div>

            {/* categories & search*/}
            <div className="flex justify-between mb-4">
                <nav className="categories flex items-end">
                    {allCategories.map(
                        (item) => (

                            <button
                                key={item.id}
                                className={
                                    activeCategory === item.name
                                        ? "category-item active"
                                        : "category-item"
                                }
                                onClick={() =>
                                    handleClickCategory(
                                        item.name
                                    )
                                }
                            >
                                {item.name}
                            </button>

                        )
                    )}

                </nav>
                <div className="search input-group">
                    <input
                        value={searchText}
                        onChange={(event) =>
                            setSearchText(
                                event.target.value
                            )
                        }
                        type="text"
                        className="form-control"
                        placeholder="search..."
                    />
                    <i
                        className="bi bi-search input-group-text search-icon"
                        onClick={handleSearch}
                    />
                </div>
            </div>
            
            {/* blog list */}
            <div className="blog-list">
                {loading && (
                    <div className="blog-loading">
                        <div
                            className="spinner-border"
                            role="status"
                        >
                            <span className="visually-hidden">
                                Loading...
                            </span>
                        </div>
                    </div>

                )}
                {allBlogs.map(
                    (blog) => (
                        <div
                            key={blog.id}
                            className="blog-card"
                            style={{
                                backgroundImage:
                                    `url(${SERVER_URL}${blog.cover_image})`
                            }}
                        >
                            <div className="blog-overlay">
                                <h2>
                                    {blog.title}
                                </h2>
                                <p className="date">
                                    {formatDate(
                                        blog.created_at
                                    )}
                                </p>

                                <div className="card-actions">
                                    <button
                                        className="btn btn-pink"
                                        onClick={() =>
                                            handleClickViewPost(
                                                blog.id
                                            )
                                        }
                                    >
                                        View Post
                                    </button>

                                    {isAdmin && (
                                        <button
                                            className="btn btn-outline-pink"
                                            onClick={() =>
                                                handleClickEdit(
                                                    blog.id
                                                )
                                            }
                                        >
                                            Edit
                                        </button>

                                    )}
                                    {isAdmin && (
                                        <button
                                            className="btn btn-outline-pink"
                                            onClick={() =>
                                                handleDeleteBtn(
                                                    blog
                                                )
                                            }
                                        >
                                            Delete
                                        </button>
                                    )}
                                </div>
                            </div>
                        </div>
                    )
                )}
            </div>

            {/* no data */}

            {!loading &&
                allBlogs.length === 0 && (

                <div className="no-data flex justify-center">

                    <img
                        src="/src/assets/imgs/no-data.png"
                        width="200"
                        alt="No data"
                    />

                </div>

            )}

            {/* delete modal */}

            {selectedBlog && (

                <div
                    className="modal fade show delete-modal"
                    style={{
                        display: "block"
                    }}
                    tabIndex="-1"
                >

                    <div className="modal-dialog">

                        <div className="modal-content">

                            <div className="modal-header">

                                <h1 className="modal-title fs-5">
                                    {selectedBlog.title}
                                </h1>

                                <button
                                    type="button"
                                    className="btn-close"
                                    onClick={() =>
                                        setSelectedBlog(
                                            null
                                        )
                                    }
                                />

                            </div>

                            <div className="modal-body">

                                Are you sure you want
                                to delete this item?

                            </div>

                            <div className="modal-footer">

                                <button
                                    type="button"
                                    className="btn btn-secondary"
                                    onClick={() =>
                                        setSelectedBlog(
                                            null
                                        )
                                    }
                                >
                                    Close
                                </button>

                                <button
                                    type="button"
                                    className="btn btn-danger"
                                    disabled={deleting}
                                    onClick={
                                        handleDelete
                                    }
                                >
                                    {deleting
                                        ? "Deleting..."
                                        : "Sure"
                                    }
                                </button>

                            </div>

                        </div>

                    </div>

                </div>

            )}

            {/* Modal backdrop */}
            {selectedBlog && (

                <div
                    className="modal-backdrop fade show"
                    onClick={() =>
                        setSelectedBlog(null)
                    }
                />

            )}

        </div>
    );
};

export default HomePage;

// project_vue/src/views/HomePage.vue
<template>
 <div class="homepage">
    <div class="header flex items-center justify-between mb-3">
        <h3 class="title">Iris Notes</h3>
        <div class="flex items-end">
            <RouterLink class="about-link" to="/about">About me</RouterLink>
            <button v-if="userStore.isAdmin" type="button" class="btn-post btn btn-pink" @click="handleClickPost">+ Post</button>
            <button v-if="!userStore.isLoggedIn" class="btn btn-outline-pink" @click="handleGoLogin">Login</button>
            <div v-if="userStore.isLoggedIn" class="flex ">
                <div class="px-4 text-2xl username">{{ userStore.user?.username }}</div>
                <button  class="btn btn-outline-pink" @click="handleLogout">Logout</button>
            </div>
        </div>
    </div>
    <div class="carousel-content">
        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel" >
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                 <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="../assets/imgs/ceramic.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="../assets/imgs/nail.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="../assets/imgs/tea.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="../assets/imgs/guzheng.png" class="d-block w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <div class="flex justify-between mb-4">
        <nav class="flex items-end ">
            <button
                v-for="item in allCategories"
                :key="item.id"
                class="category-item"
                :class="{ active: activeCategory === item.name }"
                @click="handleClickCategory(item.name)"
            >
            {{ item.name }}
            </button>
        </nav>
        <div class="search input-group">
            <input 
                v-model="searchText"
                type="text"
                class="form-control"
                placeholder="search..."
                aria-label="search" 
                aria-describedby="basic-addon2"
            >
            <i 
                class="bi bi-search search-icon input-group-text search-icon"
                id="basic-addon2"
                @click="handleSearch"
            ></i>
        </div>
    </div>
    <div class="blog-list">
        <!-- loading -->
        <Transition name="fade">
            <div
                v-if="loading"
                class="blog-loading"
            >
                <div
                    class="spinner-border"
                    role="status"
                >
                    <span class="visually-hidden">
                        Loading...
                    </span>
                </div>
            </div>
        </Transition>
        <div v-for="blog in allBlogs" :key="blog.id" class="blog-card" :style="{
            backgroundImage: `url(${SERVER_URL}${blog.cover_image})`
        }">
             <div class="blog-overlay">
                <h2>{{ blog.title }}</h2>

                <p class="date">
                    {{ formatDate(blog.created_at) }}
                </p>

                <div class="card-actions">
                    <button
                        class="btn btn-pink"
                        @click="handleClickViewPost(blog.id)"
                    >
                        view post
                    </button>

                    <button
                        v-if="userStore.isAdmin"
                        class="btn btn-outline-pink"
                        @click="handleClickEdit(blog.id)"
                    >
                        Edit
                    </button>
                    <button
                        v-if="userStore.isAdmin"
                        class="btn btn-outline-pink"
                        @click="handleDeleteBtn(blog)"
                    >
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div v-if="allBlogs && allBlogs.length == 0 && !loading" class="flex justify-center">
        <img src="../assets/imgs/no-data.png" width="200px" alt="">
    </div>
  </div>

  <!-- delete confirm modal -->
    <div ref="deleteModal"
         class="modal fade"
         id="myModal"
         tabindex="-1"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true"
    >
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">{{ selectedBlog? selectedBlog.title : '' }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" @click="handleDelete">Sure</button>
            </div>
            </div>
        </div>
    </div>
    <Toast ref="toastRef" />
</template>

<script setup>
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { getBlogsList, getCategories, searchBlogs, deleteBlog } from "../api/blog";
import { Modal } from "bootstrap";
import { useUserStore } from "../stores/user";

const userStore = useUserStore();

const SERVER_URL = import.meta.env.VITE_SERVER_URL;

const router = useRouter();
const searchText = ref("");
const activeCategory = ref("")
const allBlogs = ref([])
const allCategories = ref(null)
const loading = ref(false);
const toastRef = ref(null);

const selectedBlog = ref(null);
const deleting = ref(false);


const deleteModal = ref(null);

// get blogs list
const getBlogs = async () => {
    try {
        loading.value = true;
        const result = await getBlogsList(activeCategory.value);

        allBlogs.value = result.data;

    } catch (error) {
        console.error("Get blogs error:", error);
    } finally {
         loading.value = false;
    }
};

// click search button
const handleSearch = async () => {

    try {
        // if search text is empty, get current category blogs
        if (!searchText.value.trim()) {
            getBlogs();
            return;
        }
        const result = await searchBlogs(searchText.value);
        allBlogs.value = result.data;

    } catch (error) {

        console.error(
            "Search blogs error:",
            error
        );
    }
};

const handleClickCategory = (name) => {
    activeCategory.value = name
    getBlogs();
};

// init page
const initPage = async () => {
    try {
        const result = await getCategories();

        allCategories.value = result.data;

        if (allCategories.value.length > 0) {
            activeCategory.value =
                allCategories.value[0].name;

            await getBlogs();
        }

    } catch (error) {
        console.error("Init page error:", error);
    }
};

// click btn: view post
const handleClickViewPost = (id) => {
    router.push(`/blogDetail/${id}`)
};

// click btn: edit
const handleClickEdit = (id) => {
    router.push(`/editBlog/${id}`);
};

let deleteModalInstance = null;
// click delete btn -> show confirm model
const handleDeleteBtn = (blog) => {
    selectedBlog.value = blog;
    deleteModalInstance = Modal.getOrCreateInstance(
        deleteModal.value
    );

    deleteModalInstance.show();
};

// confirm delete
const handleDelete = async () => {
    try {
        deleting.value = true;

        await deleteBlog(selectedBlog.value.id);

        // get list again
        await getBlogs();

        // close modal
        deleteModalInstance.hide();

        toastRef.value.open({
            type: "success",
            title: "Deleted!",
            message: "The blog has been deleted successfully."
        });

    } catch (error) {

        toastRef.value.open({
            type: "error",
            title: "Delete failed",
            message: error.message
        });

    } finally {
        deleting.value = false;
    }
};

// format date
const formatDate = (date) => {
    if (!date) return "";

    return new Date(date).toLocaleDateString(
        "en-US",
        {
            year: "numeric",
            month: "short",
            day: "numeric"
        }
    );
};

onMounted(() => {
    initPage();
});

// click btn: post
const handleClickPost = () => {
    router.push("/addNewBlog");
};

// handleGoLogin
const handleGoLogin = () => {
    router.push("/login");
};

// logout
const handleLogout = () => {
    userStore.logout();

    toastRef.value.open({
        type: "success",
        title: "logout",
        message: "Logout successfully!"
    });
};

</script>

<style scoped lang="scss">
@import url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500;600;700&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600&display=swap');

input:focus {
  outline: none;
  box-shadow: none;
  border-color: #dee2e6;
}

.homepage {
    min-height: 100vh;
    padding: 0 0 20px 0;

    .header {

        .title{
            margin: 0;
            font-family: "Dancing Script", cursive;
            font-size: 48px;
            color: #E8A0B5;
        }
        .btn-post {
            width: 100px;
        }
        .username {
            font-family: "Cormorant Garamond", serif;
        }

        .about-link {
            margin-right: 35px;
            font-family: "Dancing Script", cursive;
            font-size: 30px;
            color: #E8A0B5;
            
            &:hover {
                color: #e8a0b4da;
            }
        }
    }

}

.search {
    width: 30%;
    input {
        border: 1px #E8A0B5 solid;
        color: #E8A0B5;
    }

    .search-icon {
        color: white;
        background-color: #E8A0B5 ;
        border: 1px #E8A0B5 solid;

        &:hover {
            cursor: pointer;
            color: white;
            background-color: #e8a0b4da;
        }
    }
}


/**carousel */
.carousel-content {
    margin-bottom: 30px;
}

.carousel {
    overflow: hidden;
    // height: 300px;
    background: #e4d9e8;

    .carousel-item {
        // height: 300px;
        background: #e4d9e8;
        img {
            height: 206px;
            object-fit: cover;
        }
    }
}



/**category */

.category-item {
    position: relative;
    font-family: "Cormorant Garamond", serif;
    margin-right: 30px;
    border: none;
    background: transparent;
    font-size: 22px;
    font-weight: 500;
    color: #302629;
    cursor: pointer;
    transition: 0.2s;

    &:hover {
        color: #e8a0b4da;
    }

    &.active {
        color: #E8A0B5;
        &::after {
            content: "";
            position: absolute;
            left: 0;
            bottom: 0;
            width: 100%;
            height: 4px;
            border-radius: 4px;
            background-color: #E8A0B5;
        }
    }
}

/** blog cards */
.blog-list {
    position: relative;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 26px 38px;

    .blog-loading {
        position: absolute;
        inset: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 200px;
        background-color: rgba(255, 255, 255, 0.65);
        z-index: 10;
        .spinner-border {
            width: 3rem;
            height: 3rem;
            color: #E8A0B5;
        }
    }

    .blog-card {
        position: relative;
        min-height: 235px;
        overflow: hidden;
        border-radius: 5px;
        background-color: #ebbdca86;
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        box-shadow: 0 4px 15px rgba(232, 160, 181, 0.25);

        .blog-overlay {
            position: absolute;
            inset: 0;
            display: flex;
            flex-direction: column;
            justify-content: center;
            padding: 25px;
            background-color: rgba(40, 40, 46, 0.65);
            opacity: 0;
            transition: opacity 0.3s ease;

            h2,
            .date,
            .card-actions {
                color: white;
                opacity: 0;
                transform: translateY(15px);
                transition: all 0.35s ease;
            }

            h2 {
                margin-bottom: 10px;
                font-family: "Cormorant Garamond", serif;
                font-size: 30px;
                font-weight: 600;
                display: -webkit-box;
                -webkit-box-orient: vertical;
                -webkit-line-clamp: 2;
                overflow: hidden;
                text-overflow: ellipsis;
            }

            .date {
                margin-bottom: 25px;
                font-size: 20px;
                font-family: "Cormorant Garamond", serif;
            }

            .card-actions {
                display: flex;
                gap: 12px;
            }
        }

        &:hover {
            .blog-overlay {
                opacity: 1;

                h2,
                .date,
                .card-actions {
                    opacity: 1;
                    transform: translateY(0);
                }
            }
        }
    }
}

</style>
